	@echo off
	@setlocal enabledelayedexpansion

CHOICE /N /C 123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
IF !ERRORLEVEL! EQU 35 echo Z & for /L %%n in (1,1,10) do (set /A nn=%%n*5 & echo !nn! & timeout /t !nn!)
IF !ERRORLEVEL! EQU 34 echo Y
IF !ERRORLEVEL! EQU 33 echo X
IF !ERRORLEVEL! EQU 32 goto label
IF !ERRORLEVEL! EQU 31 echo V
IF !ERRORLEVEL! EQU 30 echo U
IF !ERRORLEVEL! EQU 29 echo T
IF !ERRORLEVEL! EQU 28 (
	echo S+
	CHOICE /N /C 123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
		IF !ERRORLEVEL! EQU 35 echo S+Z
		IF !ERRORLEVEL! EQU 34 echo S+Y
		IF !ERRORLEVEL! EQU 33 echo S+X
		IF !ERRORLEVEL! EQU 32 goto label
		IF !ERRORLEVEL! EQU 31 echo S+V
		IF !ERRORLEVEL! EQU 30 echo S+U
		IF !ERRORLEVEL! EQU 29 echo S+T
		IF !ERRORLEVEL! EQU 27 echo S+R
		IF !ERRORLEVEL! EQU 26 echo S+Q
		IF !ERRORLEVEL! EQU 25 echo S+P
		IF !ERRORLEVEL! EQU 24 echo S+O
		IF !ERRORLEVEL! EQU 23 echo S+N
		IF !ERRORLEVEL! EQU 22 echo S+M
		IF !ERRORLEVEL! EQU 21 echo S+L
		IF !ERRORLEVEL! EQU 20 echo S+K
		IF !ERRORLEVEL! EQU 19 echo S+J
		IF !ERRORLEVEL! EQU 18 echo S+I
		IF !ERRORLEVEL! EQU 17 echo S+H
		IF !ERRORLEVEL! EQU 16 echo S+G
		IF !ERRORLEVEL! EQU 15 echo S+F
		IF !ERRORLEVEL! EQU 14 echo S+E
		IF !ERRORLEVEL! EQU 13 echo S+D
		IF !ERRORLEVEL! EQU 12 echo S+C
		IF !ERRORLEVEL! EQU 11 echo S+B
		IF !ERRORLEVEL! EQU 10 echo S+A
		IF !ERRORLEVEL! LSS 10 echo S+!ERRORLEVEL!
		timeout /t 30 & exit /B
)
IF !ERRORLEVEL! EQU 27 echo R
IF !ERRORLEVEL! EQU 26 echo Q
IF !ERRORLEVEL! EQU 25 echo P
IF !ERRORLEVEL! EQU 24 echo O
IF !ERRORLEVEL! EQU 23 echo N
IF !ERRORLEVEL! EQU 22 echo M
IF !ERRORLEVEL! EQU 21 echo L
IF !ERRORLEVEL! EQU 20 echo K
IF !ERRORLEVEL! EQU 19 echo J
IF !ERRORLEVEL! EQU 18 echo I
IF !ERRORLEVEL! EQU 17 echo H
IF !ERRORLEVEL! EQU 16 echo G
IF !ERRORLEVEL! EQU 15 echo F
IF !ERRORLEVEL! EQU 14 echo E
IF !ERRORLEVEL! EQU 13 echo D
IF !ERRORLEVEL! EQU 12 echo C
IF !ERRORLEVEL! EQU 11 echo B
IF !ERRORLEVEL! EQU 10 echo A
IF !ERRORLEVEL! LSS 10 echo !ERRORLEVEL!
timeout /t 30

:label
	echo label